
//! Autogenerated weights for `pallet_supply_chain_traceability`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 46.0.0
//! DATE: 2026-07-04, STEPS: `20`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `Ramys-MacBook-Pro.local`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: 1024

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/traceability-runtime/traceability_runtime.compact.compressed.wasm
// --pallet
// pallet_supply_chain_traceability
// --extrinsic
// *
// --genesis-builder
// none
// --repeat
// 20
// --steps
// 20
// --output
// weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_supply_chain_traceability`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_supply_chain_traceability::WeightInfo for WeightInfo<T> {
	/// Storage: `SupplyChain::Devices` (r:1 w:1)
	/// Proof: `SupplyChain::Devices` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SupplyChain::DeviceCount` (r:1 w:1)
	/// Proof: `SupplyChain::DeviceCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn onboard_device() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3465`
		// Minimum execution time: 35_000_000 picoseconds.
		Weight::from_parts(37_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3465))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `SupplyChain::Devices` (r:1 w:0)
	/// Proof: `SupplyChain::Devices` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SupplyChain::EventCount` (r:1 w:1)
	/// Proof: `SupplyChain::EventCount` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	/// Storage: `SupplyChain::Events` (r:0 w:1)
	/// Proof: `SupplyChain::Events` (`max_values`: None, `max_size`: None, mode: `Measured`)
	fn process_event() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `127`
		//  Estimated: `3592`
		// Minimum execution time: 39_000_000 picoseconds.
		Weight::from_parts(40_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3592))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
	/// Storage: `SupplyChain::Batches` (r:1 w:1)
	/// Proof: `SupplyChain::Batches` (`max_values`: None, `max_size`: None, mode: `Measured`)
	/// Storage: `SupplyChain::GovernanceCheckpoints` (r:1 w:1)
	/// Proof: `SupplyChain::GovernanceCheckpoints` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn evaluate_governance() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `3465`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(7_000_000, 0)
			.saturating_add(Weight::from_parts(0, 3465))
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
